### ISSUE TITLE
bug: 账号第一次登陆的location后面无法修改，但是一个账号可能会有不同的location

### ISSUE THREAD

**Issue by panzhang666** [wgr523/sp19-cs411-happy-earth#13]

**Comment by panzhang666** [comment]
每次登陆都应该submit location，default为第一次登陆时的city，state

**Comment by wgr523** [comment]
对，但不必每次。先让他不能修改吧。。以后再加一个Edit location的按钮。

**Comment by wgr523** [comment]
# 更新
再加一个按钮叫Edit Information。然后连接到一个url叫"/user/"。这个页面应该和之前那个填location的页面很像。
（详情可以找时间Skype分享屏幕）

**Comment by panzhang666** [comment]
def edit_user(request):
    # TODO
    if request.user.is_authenticated:  
        return render(request, 'happyearth/user_info.html')
我这样做可不可以？需要edit，之间返回user_info.html，重新填写

**Comment by wgr523** [comment]
应该可以，不过这个是填表（即发送POST）的部分。
还需要写接收和处理POST的部分

**Comment by panzhang666** [comment]
进入user_info.html后，不就是继续 insert user和city和stat了么？

**Comment by panzhang666** [comment]
是不是在base.html 还要加上一个Edit location的按钮啊？

**Comment by wgr523** [comment]
> 进入user_info.html后，不就是继续 insert user和city和stat了么？

我们看的是进入了哪个python函数，然后在函数里处理POST数据，而不是看进入了哪个html。
而且前几天写的那个Python函数里边是INSERT命令。现在我们需要UPDATE命令。所以才要新写一个Python函数

**Comment by wgr523** [comment]
> 是不是在base.html 还要加上一个Edit location的按钮啊？

对，不过这个可以最后再说。1分钟就能完成。

**Comment by panzhang666** [comment]
def edit_user(request):
    # TODO
    if request.user.is_authenticated:  
        return render(request, 'happyearth/user_info.html')
        if request.method.upper() == "POST":
            try:
                city = request.POST['city']
                state = request.POST['state']
                date = datetime.datetime.now().strftime("%Y-%m-%d")
                with connection.cursor() as c:
                    c.execute('INSERT IGNORE INTO happyearth_user (name, city, state, reg_date) VALUES (%s, %s, %s, %s);', [username, city, state, date])
            except:
                return HttpResponse("Error. Invalid POST request.")    

那就这个再加一次？

**Comment by panzhang666** [comment]
貌似格式都没了，等等，我改成update

**Comment by wgr523** [comment]
你加的代码需要直接加在#TODO下面，不然之前会return，意味着这个函数中断了

**Comment by panzhang666** [comment]
可是不return到user_info.html，怎么取到新location啊？

**Comment by panzhang666** [comment]
def edit_user(request):
    # TODO
    if request.user.is_authenticated:  
        return render(request, 'happyearth/user_info.html')
        if request.method.upper() == "POST":
            try:
                city = request.POST['city']
                state = request.POST['state']
                date = datetime.datetime.now().strftime("%Y-%m-%d")
                with connection.cursor() as c:
                     c.execute('UPDATE happyearth_user SET city = %s, state = %s WHERE name = %s', [city, state, username])
            except:
                return HttpResponse("Error. Invalid POST request.")  
reg_date需要改成更新时的date吗？还是不用动？

**Comment by wgr523** [comment]
> def edit_user(request):
> # TODO
> if request.user.is_authenticated:
> return render(request, 'happyearth/user_info.html')
> if request.method.upper() == "POST":
> try:
> city = request.POST['city']
> state = request.POST['state']
> date = datetime.datetime.now().strftime("%Y-%m-%d")
> with connection.cursor() as c:
> c.execute('UPDATE happyearth_user SET city = %s, state = %s WHERE name = %s', [city, state, username])
> except:
> return HttpResponse("Error. Invalid POST request.")
> reg_date需要改成更新时的date吗？还是不用动？

不变吧

**Comment by panzhang666** [comment]
def edit_user(request):
    # TODO
    if request.user.is_authenticated:  
        render(request, 'happyearth/user_info.html')
        if request.method.upper() == "POST":
            try:
                city = request.POST['city']
                state = request.POST['state']
                date = datetime.datetime.now().strftime("%Y-%m-%d")
                with connection.cursor() as c:
                     c.execute('UPDATE happyearth_user SET city = %s, state = %s WHERE name = %s', [city, state, username])
            except:
                return HttpResponse("Error. Invalid POST request.")  

不return render，直接render，这样应该就不会中断？

**Comment by wgr523** [comment]
> def edit_user(request):
> # TODO
> if request.user.is_authenticated:
> return render(request, 'happyearth/user_info.html')
> if request.method.upper() == "POST":
> try:
> city = request.POST['city']
> state = request.POST['state']
> date = datetime.datetime.now().strftime("%Y-%m-%d")
> with connection.cursor() as c:
> c.execute('UPDATE happyearth_user SET city = %s, state = %s WHERE name = %s', [city, state, username])
> except:
> return HttpResponse("Error. Invalid POST request.")
> reg_date需要改成更新时的date吗？还是不用动？

你试试用
\```
\```
这两行特殊字符把你的代码包起来，看看格式是不是就有了

**Comment by wgr523** [comment]
> def edit_user(request):
> # TODO
> if request.user.is_authenticated:
> render(request, 'happyearth/user_info.html')
> if request.method.upper() == "POST":
> try:
> city = request.POST['city']
> state = request.POST['state']
> date = datetime.datetime.now().strftime("%Y-%m-%d")
> with connection.cursor() as c:
> c.execute('UPDATE happyearth_user SET city = %s, state = %s WHERE name = %s', [city, state, username])
> except:
> return HttpResponse("Error. Invalid POST request.")
> 
> 不return render，直接render，这样应该就不会中断？

这样是不对的。重点在好几个并列的if之间，谁先谁后的问题

**Comment by panzhang666** [comment]
```
def edit_user(request):
    # TODO
    if request.user.is_authenticated:  
        render(request, 'happyearth/user_info.html')
        if request.method.upper() == "POST":
            try:
                city = request.POST['city']
                state = request.POST['state']
                date = datetime.datetime.now().strftime("%Y-%m-%d")
                with connection.cursor() as c:
                     c.execute('UPDATE happyearth_user SET city = %s, state = %s WHERE name = %s', [city, state, username])
            except:
                return HttpResponse("Error. Invalid POST request.")  
```

**Comment by panzhang666** [comment]
```
def edit_user(request):
    # TODO
    if request.user.is_authenticated:
        username = request.user.get_username()
        render(request, 'happyearth/user_info.html')
        if request.method.upper() == "POST":
            try:
                city = request.POST['city']
                state = request.POST['state']
                with connection.cursor() as c:
                     c.execute('UPDATE happyearth_user SET city = %s, state = %s WHERE name = %s', [city, state, username])
            except:
                return HttpResponse("Error. Invalid POST request.") 
```

**Comment by panzhang666** [comment]
感觉不是很对，一开始request是edit，后面的request理论应该变成进入user_info.html？

**Comment by wgr523** [comment]
必须在render前加return

**Comment by wgr523** [comment]
用户进入user info的方法不是POST，所以当method不是POST的时候，return render user info。而当是POST时，进行SQL命令

**Comment by wgr523** [comment]
然后return另一个东西，可以redirect到hoempage去

**Comment by wgr523** [comment]
POST指的是用户提交了一个填的表。而其他地方用户没有提交什么表格的时候，一般是GET method。这解释了“进入user info的方法不是POST”

**Comment by panzhang666** [comment]
```
def edit_user(request):
    # TODO
    if request.user.is_authenticated:
        username = request.user.get_username()
        if request.method.upper() == "POST":
            try:
                city = request.POST['city']
                state = request.POST['state']
                with connection.cursor() as c:
                     c.execute('UPDATE happyearth_user SET city = %s, state = %s WHERE name = %s', [city, state, username])
                return render(request, 'happyearth/user_home.html')
            except:
                return HttpResponse("Error. Invalid POST request.") 
        else:
            render(request, 'happyearth/user_info.html')
```
懂了，这样？
