### ISSUE TITLE
删除自己所有账户信息的功能

### ISSUE THREAD

**Issue by wgr523** [wgr523/sp19-cs411-happy-earth#16]

**Comment by wgr523** [comment]
已经有了一个trigger删除comment等等，只需要删除user即可

**Comment by rongqip** [comment]
def clear_user(request):
    # TODO
    if request.user.is_authenticated:
        username = request.user.get_username()
        with connection.cursor() as c:
            c.execute('DELETE FROM happyearth_user WHERE name = %s', [username])
    return HttpResponseRedirect(reverse('homepage'))

这个问题里， WHERE name = %s', [username]， 这个地方%s 代表的是username吗？

**Comment by wgr523** [comment]
对
